// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_keystore.Data;

#nullable disable

namespace backendkeystore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230223150245_EANCAmpaign")]
    partial class EANCAmpaign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_keystore.Models.EAN.EANCampaign", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("CampaignEAN")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("EANCampaign");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CampaignEAN = 5000112637922L
                        },
                        new
                        {
                            Id = "2",
                            CampaignEAN = 5000112637939L
                        },
                        new
                        {
                            Id = "3",
                            CampaignEAN = 7310865004703L
                        },
                        new
                        {
                            Id = "4",
                            CampaignEAN = 7340005404261L
                        },
                        new
                        {
                            Id = "5",
                            CampaignEAN = 7310532109090L
                        },
                        new
                        {
                            Id = "6",
                            CampaignEAN = 7611612222105L
                        });
                });

            modelBuilder.Entity("backend_keystore.Models.Products.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CampaignReceiptId")
                        .HasColumnType("text");

                    b.Property<long>("EAN")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalPriceReceiptId")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CampaignReceiptId");

                    b.HasIndex("NormalPriceReceiptId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            EAN = 5000112637922L,
                            Name = "Coca-cola",
                            Price = 19.949999999999999
                        },
                        new
                        {
                            Id = "2",
                            EAN = 5000112637939L,
                            Name = "Sprite",
                            Price = 19.949999999999999
                        },
                        new
                        {
                            Id = "3",
                            EAN = 7310865004703L,
                            Name = "Pepsi",
                            Price = 19.949999999999999
                        },
                        new
                        {
                            Id = "4",
                            EAN = 7340005404261L,
                            Name = "Seven-upp",
                            Price = 19.949999999999999
                        },
                        new
                        {
                            Id = "5",
                            EAN = 7310532109090L,
                            Name = "Fanta",
                            Price = 19.949999999999999
                        },
                        new
                        {
                            Id = "6",
                            EAN = 5000112555922L,
                            Name = "Glass",
                            Price = 19.75
                        },
                        new
                        {
                            Id = "7",
                            EAN = 5000112666622L,
                            Name = "Mjöl",
                            Price = 25.5
                        },
                        new
                        {
                            Id = "8",
                            EAN = 5000112337922L,
                            Name = "Champo",
                            Price = 18.59
                        });
                });

            modelBuilder.Entity("backend_keystore.Models.Receipts.CampaignReceipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.ToTable("CampaignReceipt");
                });

            modelBuilder.Entity("backend_keystore.Models.Receipts.NormalPriceReceipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.ToTable("NormalPriceReceipt");
                });

            modelBuilder.Entity("backend_keystore.Models.Receipts.Receipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Receipt");
                });

            modelBuilder.Entity("backend_keystore.Models.Products.Product", b =>
                {
                    b.HasOne("backend_keystore.Models.Receipts.CampaignReceipt", null)
                        .WithMany("shoppingCart")
                        .HasForeignKey("CampaignReceiptId");

                    b.HasOne("backend_keystore.Models.Receipts.NormalPriceReceipt", null)
                        .WithMany("shoppingCart")
                        .HasForeignKey("NormalPriceReceiptId");
                });

            modelBuilder.Entity("backend_keystore.Models.Receipts.CampaignReceipt", b =>
                {
                    b.HasOne("backend_keystore.Models.Receipts.Receipt", "Receipt")
                        .WithOne("CampaignReceipt")
                        .HasForeignKey("backend_keystore.Models.Receipts.CampaignReceipt", "ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("backend_keystore.Models.Receipts.NormalPriceReceipt", b =>
                {
                    b.HasOne("backend_keystore.Models.Receipts.Receipt", "Receipt")
                        .WithOne("NormalPriceReceipt")
                        .HasForeignKey("backend_keystore.Models.Receipts.NormalPriceReceipt", "ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("backend_keystore.Models.Receipts.CampaignReceipt", b =>
                {
                    b.Navigation("shoppingCart");
                });

            modelBuilder.Entity("backend_keystore.Models.Receipts.NormalPriceReceipt", b =>
                {
                    b.Navigation("shoppingCart");
                });

            modelBuilder.Entity("backend_keystore.Models.Receipts.Receipt", b =>
                {
                    b.Navigation("CampaignReceipt");

                    b.Navigation("NormalPriceReceipt");
                });
#pragma warning restore 612, 618
        }
    }
}
